apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-nodeport
  namespace: test-a
  labels:
    app: go-rest-api-nodeport
    version: "1.0"
spec:
  type: NodePort
  ports:
  - port: 8903
    targetPort: 8903
    protocol: TCP
  selector:
    app: go-rest-api-8903