apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-internal
  namespace: test-a
  labels:
    app: go-rest-api-internal
    version: "1.0"
spec:
  type: NodePort
  ports:
  - port: 8902
    targetPort: 8902
    protocol: TCP
  selector:
    app: go-rest-api-internal