apiVersion: v1
kind: Service
metadata:
  name: svc-go-rest-api-taint
  namespace: test-a
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: go-rest-api-taint
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
  - name: svc-go-rest-api-taint
    port: 8901
    targetPort: 8901
    protocol: TCP
  type: LoadBalancer
  selector:
    app: go-rest-api-taint
