app:
  profile: "development"
  name: "go-rest-api"
  description: "api - go-rest-api"
  version: "1.0"

server:
  port: 8901
  readTimeout: 60
  writeTimeout: 60
  idleTimeout: 60
  ctxTimeout: 60

setup:
  databaseType: "POSTGRES"
  responseTime: 30
  responseStatusCode: 200
  isRandomTime: 60
  count: 0
  liveness: true
  readiness: true

databaseRDS:
    host: host.docker.internal
    port: 5432
    schema: public
    user: admin
    password: admin
    databaseName: postgres
    db_timeout: 90
    postgres_driver: postgres

awsenv:
  aws_region: us-east-2
  aws_access_id: AKIA43VVMZVWTG5UMWWD
  aws_access_secret: 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
