app:
  profile: "development"
  name: "go-rest-api"
  description: "api - go-rest-api"
  version: "1.0"

server:
  port: 8901
  readTimeout: 60
  writeTimeout: 60
  idleTimeout: 60
  ctxTimeout: 60

setup:
  databaseType: "DYNAMO"
  responseTime: 30
  responseStatusCode: 200
  isRandomTime: 60
  count: 0
  liveness: true
  readiness: true

databaseRDS:
    host: host.docker.internal
    port: 5432
    schema: public
    user: postgres
    password: postgres
    databaseName: postgres
    db_timeout: 90
    postgres_driver: postgres

awsenv:
  aws_region: us-east-2
  aws_access_id: 
  aws_access_secret: 
  awsSsmSecretId: arn:aws:secretsmanager:us-east-2:908671954593:secret:rds-arch-secret-YHHAF2
  icUseSsm: false