apiVersion: v1
kind: Service
metadata:
  name: svc-go-rest-api
  namespace: test-a
spec:
  ports:
  - name: svc-go-rest-api
    port: 8900
    targetPort: 8900
  selector:
    app: go-rest-api
  type: LoadBalancer