apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-go-rest-api-r500-headless
    version: "1.0"
  name: svc-go-rest-api-r500-headless
  namespace: test-b
spec:
  clusterIP: None
  ports:
  - port: 8905
    protocol: TCP
    targetPort: 8900
  selector:
    app: go-rest-api-r500
  type: ClusterIP