apiVersion: v1
kind: ConfigMap
metadata:
  name: go-rest-api
  namespace: test-a
  labels:
    app: "go-rest-api"
    version: "1.0"
data:
  PORT: "8900"
  API_NAME: "go-rest-api"
  API_VERSION: "1.1"
  DATABASE_TYPE: "POSTGRES"
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "admin"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  AWS_REGION: "us-east-2"
