apiVersion: v1
kind: ConfigMap
metadata:
  name: go-rest-api-8903
  namespace: test-a
  labels:
    app: "ggo-rest-api-8903"
    version: "1.0"
data:
  PORT: "8903"
  API_NAME: "go-rest-api-8903"
  API_VERSION: "1.0"
  DATABASE_TYPE: "POSTGRES"
  DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  AWS_REGION: "us-east-2"
  IC_USE_SSM: "false"
