apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
  namespace: test-a
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
        version: "go-rest-api"
    spec:
      containers:
      - name: go-mock-api
        imagePullPolicy: Never
        image: go_rest_api:latest
        resources:
           requests:
             cpu: 125m
             memory: 100Mi
           limits:
             cpu: 200m
             memory: 250Mi
        ports:
        - containerPort: 8900
        env:
        - name: PORT
          value: "8900"
        - name: NAME_POD
          value: "pod-go-rest-api"
      terminationGracePeriodSeconds: 60
