apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: awsssm-secretstore
  namespace: test-a
  labels:
    app: go-rest-api
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awsssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awsssm-secret
            key: secret-access-key
