apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: test-a
  labels:
    app: go-rest-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awsssm-secretstore
    kind: SecretStore
  target:
    name: rds-secret-external-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rds-secret