apiVersion: v1
kind: Service
metadata:
  name: svc-go-rest-api
  namespace: test-a
spec:
  ports:
  - name: svc-go-rest-api
    protocol: TCP
    port: 8900
    targetPort: 8900
  - name: svc-go-rest-api-pprof
    protocol: TCP
    port: 6060
    targetPort: 6060
  selector:
    app: go-rest-api
  type: LoadBalancer