apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-arch-secret-sa
  namespace: test-b
  labels:
    app: go-rest-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awsssm-rds-arch-secretstore-sa
    kind: SecretStore
  target:
    name: rds-secret-external-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rds-arch-secret