apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-go-rest-api
  namespace: test-b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-rest-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
