apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: awsssm-rds-arch-secretstore-sa
  namespace: test-b
  labels:
    app: go-rest-api
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: go-rest-api