apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-nodeport
  namespace: test-b
  labels:
    app: go-rest-api-nodeport
    version: "1.0"
spec:
  type: NodePort
  ports:
  - port: 8900
    targetPort: 8900
    protocol: TCP
  selector:
    app: go-rest-api