apiVersion: v1
kind: Service
metadata:
  name: svc-go-rest-api-r500
  namespace: test-b
  labels:
    app: svc-go-rest-api-r500
    version: "1.0"
spec:
  type: ClusterIP
  ports:
  - port: 8905
    targetPort: 8900
    protocol: TCP
  selector:
    app: go-rest-api-r500