apiVersion: v1
kind: Service
metadata:
  name: svc-go-rest-api-best-effort
  namespace: test-b
  labels:
    app: svc-go-rest-api-best-effort
    version: "1.0"
spec:
  type: NodePort
  ports:
  - port: 8902
    targetPort: 8900
    protocol: TCP
  selector:
    app: go-rest-api-best-effort